### ISSUE TITLE
Cannot click Labels in UWP app made with Xamarin.Forms 2.5.0

### ISSUE THREAD

**Issue by jsbakker** [Microsoft/WinAppDriver#341]
I have logged this as a [Xamarin.Forms issue here](https://github.com/xamarin/Xamarin.Forms/issues/1589) since the issue started occurring after a Xamarin.Forms update, but it is also probably relevant to track this on the WinAppDriver side. If under the hood Xamarin.Forms stopped mapping the abstracted Label element into a native Windows control that can be clicked on, then there should be some sort of plan to be able to continue automating these things.

### Steps to Reproduce

1. Find the element representing the Label (Selenium Ruby example below)
> `label = driver.find_elements(:name, "LabelName")`
2. The above returns an array with 1 element. Now, click on the element
> `label[0].click()`

### Expected Behavior
The clickable item containing the Label will respond to the click request on the label.

### Actual Behavior
> `label[0].click()`

```NoMethodError: undefined method `[]' for nil:NilClass
from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:82:in `add_backtrace'```

### Reproduction Link
I have reproduced expected working functionality with XF 2.4.0.280 in a standalone app. After updating to 2.5.0 the error is reproduced. See Readme.md in the zip file for reproduction setup.

[LabelClickable.zip](https://github.com/xamarin/Xamarin.Forms/files/1633244/LabelClickable.zip)

**Comment by jsbakker** [comment]
I have found a workaround for that, which is to make InputTransparent = true on the Label itself in the application's View code. This is good for situations where the Label's parent is handling the click. In cases where the Label has a TapGestureRecognizer, this is not an appropriate solution.

**Comment by hassanuz** [comment]
Closing this issue as this is being tracked on[ Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/issues/1589).
